### ISSUE TITLE
If a command is interrupted with CTRL+C, it's not been saved into history

### ISSUE THREAD

**Issue by MyraHel** [myral/NetWizard#1]
Example:

`arp_monitor 192.168.0.1 eth0`
`CTRL+C`

The above command won't be saved into history.

**Comment by chrean** [comment]
This is not the issue. This can be "fixed" by trapping CTRL+C so the user can't leave the nwshell. Do we want that?

**Comment by MyraHel** [comment]
I've yet trapped sigint... I'm not a noob

Il 22 ago 2017 17:51, "chrean" <notifications@github.com> ha scritto:

This is not the issue. This can be "fixed" by trapping CTRL+C so the user
can't leave the nwshell. Do we want that?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/myral/NetWizard/issues/1#issuecomment-324069891>, or mute
the thread

**Comment by chrean** [comment]
Was not. Only ^D was trapped.
I've pushed a fix to trap ^C as well and now it properly saves the history even then.
